[curXs, curYs] ...
    = meshgrid(coverageMapsEHataXLabels{idxH}, ...
    coverageMapsEHataYLabels{idxH});
[curLats, curLons] ...
    = utm2deg(curXs(:), curYs(:), ...
    repmat(UTM_ZONE, length(curXs(:)), 1));

%%
hCurPLMap = figure;
hold on;
hTxs = plot3(cellAntsLatLon(:,2), cellAntsLatLon(:,1), ...
    ones(length(cellAntsLatLon(:,1)), 1).*200, 'xr', 'LineWidth', 1.5);
plot3k([curLons curLats ...
    coverageMapsEHata{idxH}(:)], ...
    'Labels', {'', ...
    'Longitude (degrees)', 'Latitude (degrees)', ...
    '', 'Path Loss (dB)'});
grid on; view(2); axis tight;
legend(hTxs, 'TXs', 'Location', 'SouthEast');
plotGoogleMapAfterPlot3k(gcf, 'satellite');

%%
hCurPLMap = figure;
hold on;
boolsToShow = coverageMapsEHata{idxH}(:)>=115 ...
    & coverageMapsEHata{idxH}(:)<=150;
hTxs = plot3(cellAntsLatLon(:,2), cellAntsLatLon(:,1), ...
    ones(length(cellAntsLatLon(:,1)), 1).*200, 'xr', 'LineWidth', 1.5);
plot3k([curLons(boolsToShow) curLats(boolsToShow) ...
    coverageMapsEHata{idxH}(boolsToShow)], ...
    'Labels', {'', ...
    'Longitude (degrees)', 'Latitude (degrees)', ...
    '', 'Path Loss (dB)'});
grid on; view(2); axis tight;
legend(hTxs, 'TXs', 'Location', 'SouthEast');
plotGoogleMapAfterPlot3k(gcf, 'satellite');